<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.wanda.epc</groupId>
        <artifactId>iot_epc_dependencies</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>iot_epc_ft</artifactId>
    <name>iot_epc_ft</name>
    <version>1.0.0-R20240911</version>

    <dependencies>
        <dependency>
            <groupId>com.wanda.epc</groupId>
            <artifactId>iot_epc_common</artifactId>
            <version>${iot_epc_common.version}</version>
        </dependency>
        <!-- modbus4j -->
        <dependency>
            <groupId>com.digitalpetri.modbus</groupId>
            <artifactId>modbus-master-tcp</artifactId>
            <version>1.1.1</version>
        </dependency>
    </dependencies>

</project>
