server:
  port: 8101
mqtt:
  hostUrl: tcp://127.0.0.1:1883
  username: admin
  password: public
  client-id: IOT-EPC-FT
  cleanSession: true
  reconnect: true
  keepAlive: 100
  isOpen: true
  qos: 1

spring:
    #redis配置
  redis:
    host: 10.60.7.50
    port: 16379
    password:

beanName: otisTcpFT

#广场ID及GatewayId
epc:
  gatewayId: FT
  gcId: 3601130010
  subsystem: dtxt/
  threadNum: 1
  cron: 0/30 * * * * ?
modbus:
  serverIP: 192.168.10.89
  port: 502


