server:
  port: 8101
mqtt:
  hostUrl: tcp://127.0.0.1:1883
  username: admin
  password: public
  client-id: IOT-EPC-FT
  cleanSession: true
  reconnect: true
  keepAlive: 100
  isOpen: true
  qos: 1

spring:
  profiles:
    active: quanzhou_puxi
    #redis配置
  redis:
    host: 10.60.7.50
    port: 16379
    password:

beanName: otisTcpFT


